### PR TITLE
Docker bugfix #3.

### PR DESCRIPTION
**Pull request by didactic-drunk**

### CODE REVIEW

**Comment by m-o-e** [comment]
`docker run -ti crystallang/crystal:latest /bin/bash -c -- "echo >shard.yml -e 'name: test\nversion: 0.0.1\ndependencies:\n  sodium:\n    github: didactic-drunk/sodium.cr\n    commit: 633f9c1621c21bcc429625cbf074f98a84a932ca'; shards && echo >test.cr 'require \"sodium\"'; crystal test.cr"`

Yup, that's an improvement.
Doesn't fail `shards` or the build, but at least prints
the wget error on top, which leads in the right direction.

**Comment by didactic-drunk** [comment]
Think I got it.  Verify?

**Comment by m-o-e** [comment]
`docker run -ti crystallang/crystal:latest /bin/bash -c -- "echo >shard.yml -e 'name: test\nversion: 0.0.1\ndependencies:\n  sodium:\n    github: didactic-drunk/sodium.cr\n    commit: 57f6467'; shards && (echo >test.cr 'require \"sodium\"'; crystal test.cr)"`

Noice! :+1:

Now it fails on `shards` exactly like it should. :)

**Comment by m-o-e** [comment]
`docker run -ti crystallang/crystal:latest /bin/bash -c -- "apt update; apt install wget; echo >shard.yml -e 'name: test\nversion: 0.0.1\ndependencies:\n  sodium:\n    github: didactic-drunk/sodium.cr\n    commit: 57f6467'; shards && (echo >test.cr 'require \"sodium\"'; crystal test.cr)"`

PS: And works fine when `wget` is present. Also as it should. 👌

**Pull request merged**
